### ISSUE TITLE
setVolume() affects all samples instead of one

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/MK-1#7]
To hear this effect, hold down one key to loop a sample, then press and release another key a few times.

I'd like to use setVolume() to create a release effect, decaying the sound after you release the key. 

https://github.com/ericrosenbaum/MK-1/blob/gh-pages/sketch.js#L487

any ideas @therewasaguy? thanks!

**Comment by therewasaguy** [comment]
Hey Eric,

It was an issue with using jQuery.extend to create new soundFiles: they all referenced the same output gain node.

This returns `true`
`audioSamples[0].output === audioSamples[2].output`

while creating a new soundFile this way returns `false`

```
mySound = loadSound('sounds/vibraphone.wav');
audioSamples[0].output === mySound.output
```

I've not used the jQuery.extend function before, but it is definitely a faster way to load the page than loading multiple files each time. I tried doing it with multiple loadSounds('...wav') but that slows things down. So I just sent a [pull request](https://github.com/ericrosenbaum/MK-1/pull/8) with an [initSampler function](https://github.com/ericrosenbaum/MK-1/pull/8/files#diff-9f2094443505273ff51ea1d1702e4367R120) that initializes a bunch of empty SoundFile objects. Then, in analyzeNewSample, instead of jQuery.extend, we can [pass a reference to the buffer only](https://github.com/ericrosenbaum/MK-1/pull/8/files#diff-9f2094443505273ff51ea1d1702e4367L417).
